<?php
/**
 * @file
 * Code for the Library Discover Page feature.
 */

include_once 'library_discover_page.features.inc';

/**
 * Implements hook_form_alter().
 * @see http://drupal.org/node/1079826 for more information on this code.
 */
function library_discover_page_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form_state['view']->name == 'browse_scenarios') {
    // dpm($form);
  }
}
